name: Larastan

on:
  workflow_dispatch:
  push:

permissions: { }

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  larastan:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run actionlint
        run: |
          set -x
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: ${{ env.PHP-VERSION }}
          ini-values: date.timezone=${{ env.TZ }}
          extensions: bcmath zip intl pdo_pgsql

      - name: Copy .env
        run: cp .env.example .env

      - name: Use Composer Cache
        id: composer-cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --quiet --no-interaction --no-ansi --no-scripts --no-progress --prefer-dist

      - name: Run Larastan Analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=1G
